// Данный файл модели был создан вручную для демонстрации

import { Channel } from './GetAllChannelsQueryResult';

/**
 * test-chat API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// Вернули с бэка только что добавленный канал

export interface CreateChannelCommandResult {
   channel: Channel;
}
