// Данный файл модели был создан вручную для демонстрации

/**
 * test-chat API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// В случае с SQRS паттерном была бы обертка над каналом, упрощено из-за фейкового бэка
// export interface GetAllChannelQueryDefinition {
//    channel: Channel;
// }

/**
 * Возвращает все каналы
 */
export interface Channel {
   id: number;
   name: string;
}
