// Данный файл модели был создан вручную для демонстрации

/**
 * test-chat API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Возвращает сообщения канала по ИД канала
 */
export interface GetChannelMessagesQueryResult {
   messages: Array<MessageData>;
}

export interface MessageData {
   id: number;
   fromUser: number;
   content: string;
   channelId: number;
}
