// Данный файл сервиса был создан вручную для демонстрации

import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { User } from '../model/GetAllUsersQueryResult';
import { LoginControl } from '../../../components/login/login.component';
import { LoginCommandResult } from '../model/LoginCommandResult';
import { Channel } from '../model/GetAllChannelsQueryResult';
import { CreateChannelCommandResult } from '../model/CreateChannelCommandResult';

/**
 * test-chat API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.*/

@Injectable({
   providedIn: 'root',
})
export class UserService {
   protected basePath = 'http://localhost:3000';

   constructor(protected httpClient: HttpClient) {}

   /**
    * Получение всех пользователей
    */
   public getUsers(): Observable<User[]> {
      return this.httpClient.request<User[]>(
         'get',
         `${this.basePath}/users`,
         {},
      );
   }

   /**
    * Авторизация
    */
   public login(body?: LoginControl): Observable<LoginCommandResult> {
      return this.httpClient.request<LoginCommandResult>(
         'post',
         `${this.basePath}/login`,
         {
            body: body,
         },
      );
   }
}
