// Данный файл сервиса был создан вручную для демонстрации

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';
import { User } from '../model/GetAllUsersQueryResult';

/**
 * test-chat API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.*/

@Injectable({
   providedIn: 'root',
})
export class UserService {
   protected basePath = 'http://localhost:3000';
   public defaultHeaders = new HttpHeaders();
   // public configuration = new Configuration();

   // constructor(
   //    protected httpClient: HttpClient,
   //    @Optional() @Inject(BASE_PATH) basePath: string,
   // ) {
   //    if (basePath) {
   //       this.basePath = basePath;
   //    }
   // }

   constructor(protected httpClient: HttpClient) {}

   /**
    * Получение всех пользователей
    */
   public getUsers(): Observable<User[]> {
      return this.httpClient.request<User[]>(
         'get',
         `${this.basePath}/users`,
         {},
      );
   }
}
